### ISSUE TITLE
Upgrade to graphql-php 0.6

### ISSUE THREAD

**Issue by mrbarletta** [4rthem/graphql-mapper#2]
Hey, great tool! 

I was wondering if you are going to upgrade it to support latest graphql-php.

**Comment by 4rthem** [comment]
Hi, thanks!

I don't know if graphql-php respects [semantic versioning](http://semver.org/) but I've set the [caret](https://getcomposer.org/doc/articles/versions.md#caret) constraint in [composer.json](https://github.com/4rthem/graphql-mapper/blob/master/composer.json#L20) so it should match `0.6`.

Because this library is still a WIP project, I haven't written integration tests yet. But feel free to report BC breaks and contribute!

**Comment by mrbarletta** [comment]
Thanks for your quick reply 4rthem.
- arthem/graphql-mapper 0.0.1 requires webonyx/graphql-php ^0.5.0 -> no matching package found.

Thats what happens when I require your package on an existing project with  "webonyx/graphql-php": "^0.6.2" already on composer.json.

**Comment by 4rthem** [comment]
Sorry I didn't notice this from [the documentation](https://getcomposer.org/doc/articles/versions.md#caret)

> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`

It's now fixed as the version constraint is `>=0.5.0`
