### ISSUE TITLE
Working example / Demo

### ISSUE THREAD

**Issue by mrbarletta** [4rthem/graphql-mapper#3]
I tried (and failed) to use this project on an existing (and working) graphql-php project, even failed doing it on a new one. 

Is it possible to have a working code? I would help document it more if you give me something to start with.
Thanks @4rthem

**Comment by 4rthem** [comment]
I'm sorry, it may be not enough clear but this is a Work In Progress project as mentioned in the [readme](https://github.com/4rthem/graphql-mapper#work-in-progress), a first proof of concept.

I paused the implementation due to lack of time and because GraphQL specification is still a draft.
But I'm glad to see that I got 10 stars with no communication and that you seem interested to use this mapper. I will reconsider my priorities and try to provide some examples soon.

**Comment by mrbarletta** [comment]
I think its a great project,  NodeJS has sequelize + sequelize-graphql but Doctrine has none to offer the same functionality.

Thanks! hope you find the time

**Comment by 4rthem** [comment]
@mrbarletta I've pushed two sandbox projects that could help you:
- https://github.com/4rthem/graphql-mapper-demo
- https://github.com/4rthem/graphql-mapper-demo-symfony (if you are using Symfony)
